#!/usr/bin/env bash
set -Eeuo pipefail

# Build a local OpenEvent Agent Demo runtime from an empty Ubuntu environment.
# The script installs system packages, clones all OpenEvent projects from GitHub,
# creates a Python venv, installs Python packages into that venv, and builds the
# OpenEvent server binary.

usage() {
  cat <<'USAGE'
Usage:
  scripts/bootstrap_ubuntu_venv.sh [--workdir DIR] [--skip-apt]

Options:
  --workdir DIR  Runtime workspace to create or update. Default: runtime
  --skip-apt     Do not run apt-get. Use this when system dependencies are already installed.
  -h, --help     Show this help.

Environment overrides:
  OPENEVENT_URL                  default: https://github.com/openevent-official/openevent.git
  OPENEVENT_SDK_URL              default: https://github.com/openevent-official/openevent-sdk.git
  OPENEVENT_MODULES_IM_URL       default: https://github.com/openevent-official/openevent-modules-im.git
  OPENEVENT_MODEL_PROXY_URL      default: https://github.com/openevent-official/openevent-modules-model-proxy.git
  OPENEVENT_VIEW_URL             default: https://github.com/openevent-official/openevent-view.git
  PYTHON_BIN                     default: python3
  JOBS                           default: nproc result, or 2

Run this script from an openevent-agent-demo checkout. The script does not start
the stack and does not write real IM/LLM credentials.
USAGE
}

fail() {
  printf '\nERROR: %s\n' "$*" >&2
  exit 1
}

on_error() {
  local rc="$1" line="$2" command="$3"
  printf '\nERROR: bootstrap failed at line %s while running:\n  %s\n' "$line" "$command" >&2
  printf 'Exit code: %s\n' "$rc" >&2
  printf 'Fix the error above and rerun this script. Existing clean checkouts are reused.\n' >&2
  exit "$rc"
}
trap 'on_error "$?" "$LINENO" "$BASH_COMMAND"' ERR

log() {
  printf '\n==> %s\n' "$*"
}

run() {
  log "$*"
  "$@"
}

abs_path() {
  case "$1" in
    /*) printf '%s\n' "$1" ;;
    *) printf '%s/%s\n' "$PWD" "$1" ;;
  esac
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "required command not found: $1"
}

check_python_version() {
  local python="$1"
  "$python" - <<'PY'
import sys

if sys.version_info < (3, 10):
    raise SystemExit(
        "Python 3.10+ is required. "
        "Install Python 3.10 or newer and rerun with PYTHON_BIN=/path/to/python3.10."
    )
PY
}

check_cmake_version() {
  local version
  version="$(cmake --version | awk 'NR == 1 {print $3}')"
  "$PYTHON_BIN" - "$version" <<'PY'
import sys

version = sys.argv[1]
parts = version.split(".")
try:
    major = int(parts[0])
    minor = int(parts[1])
except (IndexError, ValueError):
    raise SystemExit(f"could not parse CMake version: {version}")

if (major, minor) < (3, 20):
    raise SystemExit(
        f"CMake 3.20+ is required, found {version}. "
        "Install a newer CMake package and rerun."
    )
PY
}

require_clean_or_empty_checkout() {
  local dir="$1"
  [ -d "$dir/.git" ] || return 0
  if [ -n "$(git -C "$dir" status --porcelain)" ]; then
    fail "existing checkout has local changes: $dir
Commit, stash, or remove that directory before rerunning."
  fi
}

clone_or_update() {
  local name="$1" url="$2" dir="$3"
  if [ -d "$dir/.git" ]; then
    require_clean_or_empty_checkout "$dir"
    log "updating $name in $dir"
    git -C "$dir" remote set-url origin "$url"
    git -C "$dir" fetch --prune origin || fail "failed to fetch $name from $url"
    git -C "$dir" pull --ff-only || fail "failed to fast-forward $name; remove local divergence in $dir"
    return
  fi

  if [ -e "$dir" ]; then
    fail "$name target exists but is not a git checkout: $dir"
  fi

  log "cloning $name from $url"
  git clone "$url" "$dir" || fail "failed to clone $name from $url
Check network access and the public GitHub repository URL."
}

install_apt_packages() {
  require_command apt-get
  local packages=(
    build-essential
    cmake
    pkg-config
    protobuf-compiler
    protobuf-compiler-grpc
    libprotobuf-dev
    libgrpc++-dev
    librocksdb-dev
    libyaml-cpp-dev
    python3-dev
    python3-venv
    python3-pip
  )

  if [ "$(id -u)" -eq 0 ]; then
    run env DEBIAN_FRONTEND=noninteractive apt-get update
    run env DEBIAN_FRONTEND=noninteractive apt-get install -y "${packages[@]}"
  else
    command -v sudo >/dev/null 2>&1 || fail "apt installation requires root or sudo. Run as root, install sudo, or rerun with --skip-apt after installing system dependencies."
    run sudo env DEBIAN_FRONTEND=noninteractive apt-get update
    run sudo env DEBIAN_FRONTEND=noninteractive apt-get install -y "${packages[@]}"
  fi
}

write_stack_env() {
  local agent_dir="$1" venv_python="$2" server_bin="$3"
  local env_path="$agent_dir/openevent-stack/config/env.sh"
  mkdir -p "$(dirname "$env_path")"
  log "writing local stack environment: $env_path"
  cat >"$env_path" <<EOF
#!/usr/bin/env bash

# Generated by scripts/bootstrap_ubuntu_venv.sh.
# Local machine overrides for openevent-stack scripts.

PYTHON_BIN="\${PYTHON_BIN:-$venv_python}"
OPENEVENT_SERVER_BIN="\${OPENEVENT_SERVER_BIN:-$server_bin}"
EXTRA_PYTHONPATH="\${EXTRA_PYTHONPATH:-}"
EOF
  chmod +x "$env_path"
}

verify_python_imports() {
  local python="$1" agent_dir="$2"
  log "verifying Python runtime imports"
  PYTHONPATH="$agent_dir${PYTHONPATH:+:$PYTHONPATH}" "$python" - <<'PY'
import importlib

modules = [
    "openevent.sdk",
    "openevent.im_sdk",
    "openevent.im_p2p_syncer",
    "openevent.model_proxy",
    "openevent.model_proxy_sdk",
    "openevent.view",
    "im_model_agent",
    "yaml",
]
missing = []
for module in modules:
    try:
        importlib.import_module(module)
    except Exception as exc:
        missing.append(f"{module}: {exc}")
if missing:
    raise SystemExit("Python runtime import check failed:\n" + "\n".join(missing))
PY
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEMO_SOURCE="$(cd "$SCRIPT_DIR/.." && pwd)"
WORKDIR="$DEMO_SOURCE/runtime"
INSTALL_APT=1

while [ "$#" -gt 0 ]; do
  case "$1" in
    --workdir)
      [ "$#" -ge 2 ] || fail "--workdir requires a directory"
      WORKDIR="$2"
      shift 2
      ;;
    --skip-apt)
      INSTALL_APT=0
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      fail "unknown argument: $1"
      ;;
  esac
done

PYTHON_BIN="${PYTHON_BIN:-python3}"
OPENEVENT_URL="${OPENEVENT_URL:-https://github.com/openevent-official/openevent.git}"
OPENEVENT_SDK_URL="${OPENEVENT_SDK_URL:-https://github.com/openevent-official/openevent-sdk.git}"
OPENEVENT_MODULES_IM_URL="${OPENEVENT_MODULES_IM_URL:-https://github.com/openevent-official/openevent-modules-im.git}"
OPENEVENT_MODEL_PROXY_URL="${OPENEVENT_MODEL_PROXY_URL:-https://github.com/openevent-official/openevent-modules-model-proxy.git}"
OPENEVENT_VIEW_URL="${OPENEVENT_VIEW_URL:-https://github.com/openevent-official/openevent-view.git}"
JOBS="${JOBS:-$(nproc 2>/dev/null || printf '2')}"
export PYTHONDONTWRITEBYTECODE=1
export PIP_NO_COMPILE=1

WORKDIR="$(abs_path "$WORKDIR")"
SRC_DIR="$WORKDIR/src"
VENV_DIR="$WORKDIR/venv"

if [ "$INSTALL_APT" -eq 1 ]; then
  install_apt_packages
fi

require_command git
require_command cmake
require_command make
require_command "$PYTHON_BIN"
require_command protoc
require_command grpc_cpp_plugin
check_python_version "$PYTHON_BIN"
check_cmake_version

run mkdir -p "$SRC_DIR"

clone_or_update "OPENEVENT" "$OPENEVENT_URL" "$SRC_DIR/openevent"
clone_or_update "OPENEVENT_SDK" "$OPENEVENT_SDK_URL" "$SRC_DIR/openevent-sdk"
clone_or_update "OPENEVENT_MODULES_IM" "$OPENEVENT_MODULES_IM_URL" "$SRC_DIR/openevent-modules-im"
clone_or_update "OPENEVENT_MODEL_PROXY" "$OPENEVENT_MODEL_PROXY_URL" "$SRC_DIR/openevent-modules-model-proxy"
clone_or_update "OPENEVENT_VIEW" "$OPENEVENT_VIEW_URL" "$SRC_DIR/openevent-view"

log "initializing OpenEvent server submodules"
git -C "$SRC_DIR/openevent" submodule update --init --recursive || fail "failed to initialize OpenEvent submodules"

log "creating Python venv: $VENV_DIR"
"$PYTHON_BIN" -m venv "$VENV_DIR" || fail "failed to create venv. Install python3-venv and rerun."
VENV_PYTHON="$VENV_DIR/bin/python"

run "$VENV_PYTHON" -m pip install --upgrade --no-compile pip setuptools wheel build

run cmake -S "$SRC_DIR/openevent" -B "$SRC_DIR/openevent/build" -DCMAKE_BUILD_TYPE=Release
run cmake --build "$SRC_DIR/openevent/build" --target openevent_server -j "$JOBS"
SERVER_BIN="$SRC_DIR/openevent/build/openevent_server"
[ -x "$SERVER_BIN" ] || fail "OpenEvent server binary was not created: $SERVER_BIN"

run make -C "$SRC_DIR/openevent-sdk" PYTHON="$VENV_PYTHON" INSTALL_ARGS="--no-compile" install
run make -C "$SRC_DIR/openevent-modules-im" PYTHON="$VENV_PYTHON" INSTALL_ARGS="--no-compile" install
run make -C "$SRC_DIR/openevent-modules-model-proxy" PYTHON="$VENV_PYTHON" INSTALL_ARGS="--no-compile" install
run make -C "$SRC_DIR/openevent-view" PYTHON="$VENV_PYTHON" INSTALL_ARGS="--no-compile" install

AGENT_DIR="$DEMO_SOURCE"
write_stack_env "$AGENT_DIR" "$VENV_PYTHON" "$SERVER_BIN"
verify_python_imports "$VENV_PYTHON" "$AGENT_DIR"

cat <<EOF

Bootstrap completed.

Workspace:
  $WORKDIR

Python venv:
  $VENV_DIR

OpenEvent server:
  $SERVER_BIN

Next steps:
  source "$VENV_DIR/bin/activate"
  cd "$AGENT_DIR"
  read README.md for stack configuration and startup
EOF
